# Generated by Django 4.2.11 on 2024-05-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
