# Generated by Django 4.2.11 on 2024-05-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0005_remove_listitem_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='checked',
        ),
    ]
